Upload package

diff --git a/.github/workflows/publish_npm.yml b/.github/workflows/publish_npm.yml
--- a/.github/workflows/publish_npm.yml
+++ b/.github/workflows/publish_npm.yml
@@ -3,8 +3,6 @@ name: Deploy library on NPM
 on:
   release:
     types: [created, edited, published]
-  pull_request:
-    types: [opened, synchronize]
     
 # Declare default permissions as read only.
 permissions: read-all
@@ -53,10 +51,10 @@ jobs:
         # Fail if package name not properly configured
         run: exit 1
 
-      # - name: Check if package version matches with tag
-      #   if: github.ref != steps.get_package_info.outputs.PACKAGE_VERSION
-      #   # Fail if package version not properly setted
-      #   run: exit 1
+      - name: Check if package version matches with tag
+        if: github.ref != steps.get_package_info.outputs.PACKAGE_VERSION
+        # Fail if package version not properly setted
+        run: exit 1
       
       - name: Check if package repository matches with repository
         if: github.repositoryUrl != steps.get_package_info.outputs.PACKAGE_REPOSITORY
@@ -100,34 +98,34 @@ jobs:
 
           echo "Version $PACKAGE_VERSION of $PACKAGE_NAME is not published. Proceeding with publishing..."
 
-      # - name: Upload package
-      #   run: npm publish
+      - name: Upload package
+        run: npm publish
       
-      # - name: Post upload validation
-      #   id: unpack
-      #   run: |
-      #     # Get the package name and version
-      #     PACKAGE_NAME=$(cat package.json | jq -r .name)
-      #     PACKAGE_VERSION=$(cat package.json | jq -r .version)
-      #     FULL_PACKAGE_NAME="${PACKAGE_NAME}@${PACKAGE_VERSION}"
+      - name: Post upload validation
+        id: unpack
+        run: |
+          # Get the package name and version
+          PACKAGE_NAME=$(cat package.json | jq -r .name)
+          PACKAGE_VERSION=$(cat package.json | jq -r .version)
+          FULL_PACKAGE_NAME="${PACKAGE_NAME}@${PACKAGE_VERSION}"
 
-      #     # Wait for package propagation
-      #     echo "Waiting for package propagation..."
-      #     sleep 15
+          # Wait for package propagation
+          echo "Waiting for package propagation..."
+          sleep 15
 
-      #     # Fetch the shasum from npm
-      #     POST_UPLOAD_HASH=$(npm view $FULL_PACKAGE_NAME dist.shasum)
-      #     echo "POST_UPLOAD_HASH=$POST_UPLOAD_HASH" >> $GITHUB_OUTPUT
-      #     echo "POST_UPLOAD_HASH: $POST_UPLOAD_HASH"
+          # Fetch the shasum from npm
+          POST_UPLOAD_HASH=$(npm view $FULL_PACKAGE_NAME dist.shasum)
+          echo "POST_UPLOAD_HASH=$POST_UPLOAD_HASH" >> $GITHUB_OUTPUT
+          echo "POST_UPLOAD_HASH: $POST_UPLOAD_HASH"
 
-      # - name: Pre and Post Upload validation
-      #   run: |
-      #     echo "Comparing hashes..."
-      #     echo "PRE_UPLOAD_HASH: '${{ steps.pack.outputs.PRE_UPLOAD_HASH }}'"
-      #     echo "POST_UPLOAD_HASH: '${{ steps.unpack.outputs.POST_UPLOAD_HASH }}'"
+      - name: Pre and Post Upload validation
+        run: |
+          echo "Comparing hashes..."
+          echo "PRE_UPLOAD_HASH: '${{ steps.pack.outputs.PRE_UPLOAD_HASH }}'"
+          echo "POST_UPLOAD_HASH: '${{ steps.unpack.outputs.POST_UPLOAD_HASH }}'"
 
-      #     if [ "${{ steps.pack.outputs.PRE_UPLOAD_HASH }}" != "${{ steps.unpack.outputs.POST_UPLOAD_HASH }}" ]; then
-      #       echo "Hash mismatch detected!"
-      #       exit 1
-      #     fi
-      #     echo "Hashes match successfully!"
+          if [ "${{ steps.pack.outputs.PRE_UPLOAD_HASH }}" != "${{ steps.unpack.outputs.POST_UPLOAD_HASH }}" ]; then
+            echo "Hash mismatch detected!"
+            exit 1
+          fi
+          echo "Hashes match successfully!"
